// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/user/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/user/internal/repository"
	"github.com/013677890/LCchat-Backend/apps/user/internal/service"
)

// Injectors from wire.go:

func initializeUserApp() (*UserApp, error) {
	loggerConfig := provideUserLoggerConfig()
	logger, err := provideUserLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	mainUserMetricsAddress := provideUserMetricsAddress()
	mySQLConfig := provideUserMySQLConfig()
	db, err := provideUserMySQLDB(logger, mySQLConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideUserRedisConfig()
	client, err := provideUserRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	iUserRepository := repository.NewUserRepository(db, client)
	iAuthRepository := repository.NewAuthRepository(db, client)
	iDeviceRepository := repository.NewDeviceRepository(db, client)
	iUserService := service.NewUserService(iUserRepository, iAuthRepository, iDeviceRepository)
	userHandler := handler.NewUserHandler(iUserService)
	iInternalProfileService := service.NewInternalProfileService(iUserRepository)
	internalProfileHandler := handler.NewInternalProfileHandler(iInternalProfileService)
	iGroupRepository := repository.NewGroupRepository(db)
	iGroupService := service.NewGroupService(iGroupRepository)
	groupHandler := handler.NewGroupHandler(iGroupService)
	registrationFunc := provideUserRegistration(userHandler, internalProfileHandler, groupHandler)
	mainUserGRPCAddress := provideUserGRPCAddress()
	builtServer, err := provideUserGRPCServer(registrationFunc, mainUserGRPCAddress)
	if err != nil {
		return nil, err
	}
	server := provideUserMetricsServer(mainUserMetricsAddress, builtServer)
	listener, err := provideUserGRPCListener(mainUserGRPCAddress)
	if err != nil {
		return nil, err
	}
	mainUserGRPCShutdownTimeout := provideUserGRPCShutdownTimeout()
	kafkaConfig := provideUserKafkaConfig()
	producer := provideUserKafkaProducer(client, kafkaConfig)
	v := provideUserRedisRetryConsumer(client, producer, kafkaConfig, logger)
	userCreatedConsumer := provideUserUserCreatedConsumer(kafkaConfig, iInternalProfileService, db)
	accountDeletedConsumer := provideUserAccountDeletedConsumer(kafkaConfig, iUserRepository, db)
	asyncConfig := provideUserAsyncConfig()
	pool, err := provideUserAsyncPool(logger, asyncConfig)
	if err != nil {
		return nil, err
	}
	mainUserAsyncReleaseTimeout := provideUserAsyncReleaseTimeout(asyncConfig)
	userApp, err := NewUserApp(logger, server, builtServer, listener, mainUserGRPCShutdownTimeout, v, userCreatedConsumer, accountDeletedConsumer, producer, pool, mainUserAsyncReleaseTimeout, db, client)
	if err != nil {
		return nil, err
	}
	return userApp, nil
}
