// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/user/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/user/internal/repository"
	"github.com/013677890/LCchat-Backend/apps/user/internal/service"
)

// Injectors from wire.go:

func initializeUserApp() (*UserApp, error) {
	loggerConfig := provideUserLoggerConfig()
	logger, err := provideUserLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	mainUserMetricsAddress := provideUserMetricsAddress()
	mySQLConfig := provideUserMySQLConfig()
	db, err := provideUserMySQLDB(logger, mySQLConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideUserRedisConfig()
	client, err := provideUserRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	iUserRepository := repository.NewUserRepository(db, client)
	userService := service.NewProfileUserService(iUserRepository)
	userHandler := handler.NewUserHandler(userService)
	internalProfileService := service.NewInternalProfileService(iUserRepository)
	internalProfileHandler := handler.NewInternalProfileHandler(internalProfileService)
	registrationFunc := provideUserRegistration(userHandler, internalProfileHandler)
	builtServer, err := provideUserGRPCServer(registrationFunc)
	if err != nil {
		return nil, err
	}
	server, err := provideUserMetricsServer(mainUserMetricsAddress, builtServer)
	if err != nil {
		return nil, err
	}
	mainUserGRPCAddress := provideUserGRPCAddress()
	listener, err := provideUserGRPCListener(mainUserGRPCAddress)
	if err != nil {
		return nil, err
	}
	mainUserGRPCShutdownTimeout := provideUserGRPCShutdownTimeout()
	kafkaConfig := provideUserKafkaConfig()
	redisRetryConsumer, err := provideUserRedisRetryConsumer(client, kafkaConfig, logger, db)
	if err != nil {
		return nil, err
	}
	userCreatedConsumer, err := provideUserUserCreatedConsumer(kafkaConfig, internalProfileService, db)
	if err != nil {
		return nil, err
	}
	accountDeletedConsumer, err := provideUserAccountDeletedConsumer(kafkaConfig, iUserRepository, db)
	if err != nil {
		return nil, err
	}
	producer := provideUserKafkaProducer(client, kafkaConfig)
	asyncConfig := provideUserAsyncConfig()
	pool, err := provideUserAsyncPool(logger, asyncConfig)
	if err != nil {
		return nil, err
	}
	mainUserAsyncReleaseTimeout := provideUserAsyncReleaseTimeout(asyncConfig)
	userApp, err := NewUserApp(logger, server, builtServer, listener, mainUserGRPCShutdownTimeout, redisRetryConsumer, userCreatedConsumer, accountDeletedConsumer, producer, pool, mainUserAsyncReleaseTimeout, db, client)
	if err != nil {
		return nil, err
	}
	return userApp, nil
}
