// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/user/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/user/internal/repository"
	"github.com/013677890/LCchat-Backend/apps/user/internal/service"
)

// Injectors from wire.go:

func initializeUserApp() (*UserApp, error) {
	loggerConfig := provideUserLoggerConfig()
	logger, err := provideUserLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	mainUserMetricsAddress := provideUserMetricsAddress()
	mySQLConfig := provideUserMySQLConfig()
	db, err := provideUserMySQLDB(logger, mySQLConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideUserRedisConfig()
	client, err := provideUserRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	iAuthRepository := repository.NewAuthRepository(db, client)
	iDeviceRepository := repository.NewDeviceRepository(db, client)
	iAuthService := service.NewAuthService(iAuthRepository, iDeviceRepository)
	authHandler := handler.NewAuthHandler(iAuthService)
	iUserRepository := repository.NewUserRepository(db, client)
	iUserService := service.NewUserService(iUserRepository, iAuthRepository, iDeviceRepository)
	userHandler := handler.NewUserHandler(iUserService)
	iFriendRepository := repository.NewFriendRepository(db, client)
	iApplyRepository := repository.NewApplyRepository(db, client)
	iBlacklistRepository := repository.NewBlacklistRepository(db, client)
	iFriendService := service.NewFriendService(iFriendRepository, iApplyRepository, iBlacklistRepository)
	friendHandler := handler.NewFriendHandler(iFriendService)
	iBlacklistService := service.NewBlacklistService(iBlacklistRepository)
	blacklistHandler := handler.NewBlacklistHandler(iBlacklistService)
	iDeviceService := service.NewDeviceService(iDeviceRepository)
	deviceHandler := handler.NewDeviceHandler(iDeviceService)
	iGroupRepository := repository.NewGroupRepository(db)
	iGroupService := service.NewGroupService(iGroupRepository)
	groupHandler := handler.NewGroupHandler(iGroupService)
	registrationFunc := provideUserRegistration(authHandler, userHandler, friendHandler, blacklistHandler, deviceHandler, groupHandler)
	mainUserGRPCAddress := provideUserGRPCAddress()
	builtServer, err := provideUserGRPCServer(registrationFunc, mainUserGRPCAddress)
	if err != nil {
		return nil, err
	}
	server := provideUserMetricsServer(mainUserMetricsAddress, builtServer)
	listener, err := provideUserGRPCListener(mainUserGRPCAddress)
	if err != nil {
		return nil, err
	}
	mainUserGRPCShutdownTimeout := provideUserGRPCShutdownTimeout()
	kafkaConfig := provideUserKafkaConfig()
	producer := provideUserKafkaProducer(client, kafkaConfig)
	redisRetryConsumer := provideUserRedisRetryConsumer(client, producer, kafkaConfig, logger)
	asyncConfig := provideUserAsyncConfig()
	pool, err := provideUserAsyncPool(logger, asyncConfig)
	if err != nil {
		return nil, err
	}
	mainUserAsyncReleaseTimeout := provideUserAsyncReleaseTimeout(asyncConfig)
	userApp, err := NewUserApp(logger, server, builtServer, listener, mainUserGRPCShutdownTimeout, redisRetryConsumer, producer, pool, mainUserAsyncReleaseTimeout, db, client)
	if err != nil {
		return nil, err
	}
	return userApp, nil
}
