apiVersion: v1
kind: Secret
metadata:
  name: lcchat-secret
type: Opaque
stringData:
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  REDIS_PASSWORD: ""
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
  EMAIL_AUTH_CODE: ""
