apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relation
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-push
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: connect
spec:
  replicas: 1
