apiVersion: v1
kind: Secret
metadata:
  name: lcchat-secret
  labels:
    app.kubernetes.io/part-of: lcchat
type: Opaque
stringData:
  MYSQL_USER: CHANGE_ME_MYSQL_USER
  MYSQL_PASSWORD: CHANGE_ME_MYSQL_PASSWORD
  REDIS_PASSWORD: ""
  MINIO_ACCESS_KEY: CHANGE_ME_MINIO_ACCESS_KEY
  MINIO_SECRET_KEY: CHANGE_ME_MINIO_SECRET_KEY
  EMAIL_AUTH_CODE: CHANGE_ME_QQ_SMTP_AUTH_CODE
