// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

func initializeMessagePushApp() (*MessagePushApp, error) {
	loggerConfig := provideMessagePushLoggerConfig()
	logger, err := provideMessagePushLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideMessagePushRedisConfig()
	client, err := provideMessagePushRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	messagePushRouteTTL := provideMessagePushRouteTTL()
	redisRepository := provideRouteRepository(client, messagePushRouteTTL)
	clientManager := provideConnectClientManager()
	messagePushConnectUserTimeout := provideMessagePushConnectUserTimeout()
	sender := provideConnectSender(clientManager, messagePushConnectUserTimeout)
	eventHandler := provideEventHandler(redisRepository, sender)
	kafkaConfig := provideMessagePushKafkaConfig()
	groupID := provideMessagePushGroupID()
	consumerConsumer := providePushConsumer(kafkaConfig, groupID, eventHandler)
	messagePushApp, err := NewMessagePushApp(logger, consumerConsumer, client, clientManager)
	if err != nil {
		return nil, err
	}
	return messagePushApp, nil
}
