// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// initializeMessagePushApp 定义 Wire 注入入口。
// 实际初始化代码由 `wire` 命令生成到 `wire_gen.go`。
func initializeMessagePushApp() (*MessagePushApp, error) {
	loggerConfig := provideMessagePushLoggerConfig()
	logger, err := provideMessagePushLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	kafkaConfig := provideMessagePushKafkaConfig()
	string2 := provideMessagePushGroupID()
	redisConfig := provideMessagePushRedisConfig()
	client, err := provideMessagePushRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	mainMessagePushRouteTTL := provideMessagePushRouteTTL()
	redisRepository := provideRouteRepository(client, mainMessagePushRouteTTL)
	clientManager := provideConnectClientManager()
	mainMessagePushConnectUserTimeout := provideMessagePushConnectUserTimeout()
	sender := provideConnectSender(clientManager, mainMessagePushConnectUserTimeout)
	mainMessagePushGroupGRPCAddress := provideMessagePushGroupGRPCAddress()
	clientConn, err := provideMessagePushGroupGRPCConn(logger, mainMessagePushGroupGRPCAddress)
	if err != nil {
		return nil, err
	}
	groupcliClient := provideGroupClient(clientConn)
	mainMessagePushMaxFanoutConcurrency, err := provideMessagePushMaxFanoutConcurrency()
	if err != nil {
		return nil, err
	}
	msgPushHandler, err := provideMsgPushHandler(redisRepository, sender, groupcliClient, mainMessagePushMaxFanoutConcurrency)
	if err != nil {
		return nil, err
	}
	mainMsgPushConsumer, err := providePushConsumer(kafkaConfig, string2, msgPushHandler)
	if err != nil {
		return nil, err
	}
	realtimeHandler := provideRealtimeHandler(redisRepository, sender, groupcliClient)
	mainRealtimePushConsumer, err := provideRealtimePushConsumer(kafkaConfig, realtimeHandler)
	if err != nil {
		return nil, err
	}
	mainPushConsumers := providePushConsumers(mainMsgPushConsumer, mainRealtimePushConsumer)
	config := provideMessagePushHTTPConfig()
	server := provideMessagePushHTTPServer(config)
	messagePushApp, err := NewMessagePushApp(logger, mainPushConsumers, client, clientManager, clientConn, server)
	if err != nil {
		return nil, err
	}
	return messagePushApp, nil
}
