// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/relation/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/relation/internal/repository"
	"github.com/013677890/LCchat-Backend/apps/relation/internal/service"
)

// Injectors from wire.go:

func initializeRelationApp() (*RelationApp, error) {
	loggerConfig := provideRelationLoggerConfig()
	logger, err := provideRelationLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	mainRelationMetricsAddress := provideRelationMetricsAddress()
	mySQLConfig := provideRelationMySQLConfig()
	db, err := provideRelationMySQLDB(logger, mySQLConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideRelationRedisConfig()
	client, err := provideRelationRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	iFriendRepository := repository.NewFriendRepository(db, client)
	iApplyRepository := repository.NewApplyRepository(db, client)
	iBlacklistRepository := repository.NewBlacklistRepository(db, client)
	kafkaConfig := provideRelationKafkaConfig()
	realtimePushProducer := provideRelationRealtimePushProducer(kafkaConfig)
	iFriendService := service.NewFriendService(db, client, iFriendRepository, iApplyRepository, iBlacklistRepository, realtimePushProducer)
	friendHandler := handler.NewFriendHandler(iFriendService)
	iBlacklistService := service.NewBlacklistService(db, client, iBlacklistRepository, iFriendRepository, realtimePushProducer)
	blacklistHandler := handler.NewBlacklistHandler(iBlacklistService)
	registrationFunc := provideRelationRegistration(friendHandler, blacklistHandler)
	mainRelationGRPCAddress := provideRelationGRPCAddress()
	builtServer, err := provideRelationGRPCServer(registrationFunc, mainRelationGRPCAddress)
	if err != nil {
		return nil, err
	}
	server := provideRelationMetricsServer(mainRelationMetricsAddress, builtServer)
	listener, err := provideRelationGRPCListener(mainRelationGRPCAddress)
	if err != nil {
		return nil, err
	}
	mainRelationGRPCShutdownTimeout := provideRelationGRPCShutdownTimeout()
	asyncConfig := provideRelationAsyncConfig()
	pool, err := provideRelationAsyncPool(logger, asyncConfig)
	if err != nil {
		return nil, err
	}
	mainRelationAsyncReleaseTimeout := provideRelationAsyncReleaseTimeout(asyncConfig)
	accountDeletedConsumer := provideRelationAccountDeletedConsumer(kafkaConfig, iFriendRepository, iApplyRepository, db)
	relationApp, err := NewRelationApp(logger, server, builtServer, listener, mainRelationGRPCShutdownTimeout, pool, mainRelationAsyncReleaseTimeout, accountDeletedConsumer, realtimePushProducer, db, client)
	if err != nil {
		return nil, err
	}
	return relationApp, nil
}
