// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/relation/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/relation/internal/repository"
	"github.com/013677890/LCchat-Backend/apps/relation/internal/service"
)

// Injectors from wire.go:

func initializeRelationApp() (*RelationApp, error) {
	loggerConfig := provideRelationLoggerConfig()
	logger, err := provideRelationLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	mainRelationMetricsAddress := provideRelationMetricsAddress()
	mySQLConfig := provideRelationMySQLConfig()
	db, err := provideRelationMySQLDB(logger, mySQLConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideRelationRedisConfig()
	client, err := provideRelationRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	iFriendRepository := repository.NewFriendRepository(db, client)
	iApplyRepository := repository.NewApplyRepository(db, client)
	iBlacklistRepository := repository.NewBlacklistRepository(db, client)
	mainRelationAuthGRPCAddress := provideRelationAuthGRPCAddress()
	mainRelationAuthGRPCConn, err := provideRelationAuthGRPCConn(logger, mainRelationAuthGRPCAddress)
	if err != nil {
		return nil, err
	}
	accountChecker := provideRelationAccountChecker(mainRelationAuthGRPCConn)
	kafkaConfig := provideRelationKafkaConfig()
	producer := provideRelationRealtimePushProducer(kafkaConfig)
	iFriendService := service.NewFriendService(iFriendRepository, iApplyRepository, iBlacklistRepository, accountChecker, producer)
	friendHandler := handler.NewFriendHandler(iFriendService)
	iBlacklistService := service.NewBlacklistService(iBlacklistRepository, producer)
	blacklistHandler := handler.NewBlacklistHandler(iBlacklistService)
	registrationFunc := provideRelationRegistration(friendHandler, blacklistHandler)
	builtServer, err := provideRelationGRPCServer(registrationFunc)
	if err != nil {
		return nil, err
	}
	server, err := provideRelationMetricsServer(mainRelationMetricsAddress, builtServer)
	if err != nil {
		return nil, err
	}
	mainRelationGRPCAddress := provideRelationGRPCAddress()
	listener, err := provideRelationGRPCListener(mainRelationGRPCAddress)
	if err != nil {
		return nil, err
	}
	mainRelationGRPCShutdownTimeout := provideRelationGRPCShutdownTimeout()
	asyncConfig := provideRelationAsyncConfig()
	pool, err := provideRelationAsyncPool(logger, asyncConfig)
	if err != nil {
		return nil, err
	}
	mainRelationAsyncReleaseTimeout := provideRelationAsyncReleaseTimeout(asyncConfig)
	redisRetryConsumer, err := provideRelationRedisRetryConsumer(client, kafkaConfig, logger, db)
	if err != nil {
		return nil, err
	}
	accountDeletedConsumer, err := provideRelationAccountDeletedConsumer(kafkaConfig, iFriendRepository, iApplyRepository, db)
	if err != nil {
		return nil, err
	}
	kafkaProducer := provideRelationRedisRetryProducer(client, kafkaConfig)
	relationApp, err := NewRelationApp(logger, server, builtServer, listener, mainRelationGRPCShutdownTimeout, pool, mainRelationAsyncReleaseTimeout, redisRetryConsumer, accountDeletedConsumer, kafkaProducer, producer, mainRelationAuthGRPCConn, db, client)
	if err != nil {
		return nil, err
	}
	return relationApp, nil
}
