// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/relation/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/relation/internal/repository"
	"github.com/013677890/LCchat-Backend/apps/relation/internal/service"
)

// initializeRelationApp 由 Wire 生成的依赖注入函数。
// 请在修改 wire.go 后运行 wire ./apps/relation/cmd/ 重新生成。
func initializeRelationApp() (*RelationApp, error) {
	loggerConfig := provideRelationLoggerConfig()
	zapLogger, err := provideRelationLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	asyncConfig := provideRelationAsyncConfig()
	pool, err := provideRelationAsyncPool(zapLogger, asyncConfig)
	if err != nil {
		return nil, err
	}
	timeout := provideRelationAsyncReleaseTimeout(asyncConfig)
	mysqlConfig := provideRelationMySQLConfig()
	db, err := provideRelationMySQLDB(zapLogger, mysqlConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideRelationRedisConfig()
	client, err := provideRelationRedisClient(zapLogger, redisConfig)
	if err != nil {
		return nil, err
	}

	// Repository
	friendRepo := repository.NewFriendRepository(db, client)
	applyRepo := repository.NewApplyRepository(db, client)
	blacklistRepo := repository.NewBlacklistRepository(db, client)

	// Service
	friendService := service.NewFriendService(db, client, friendRepo, applyRepo)
	blacklistService := service.NewBlacklistService(db, client, blacklistRepo, friendRepo)

	// Handler
	friendHandler := handler.NewFriendHandler(friendService)
	blacklistHandler := handler.NewBlacklistHandler(blacklistService)

	// gRPC
	registrationFunc := provideRelationRegistration(friendHandler, blacklistHandler)
	grpcAddress := provideRelationGRPCAddress()
	builtServer, err := provideRelationGRPCServer(registrationFunc, grpcAddress)
	if err != nil {
		return nil, err
	}
	listener, err := provideRelationGRPCListener(grpcAddress)
	if err != nil {
		return nil, err
	}

	// Metrics
	metricsAddress := provideRelationMetricsAddress()
	metricsServer := provideRelationMetricsServer(metricsAddress, builtServer)

	// Timeouts
	grpcShutdownTimeout := provideRelationGRPCShutdownTimeout()

	relationApp, err := NewRelationApp(
		zapLogger,
		metricsServer,
		builtServer,
		listener,
		grpcShutdownTimeout,
		pool,
		timeout,
		db,
		client,
	)
	if err != nil {
		return nil, err
	}
	return relationApp, nil
}
