// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/msg/internal/domain/conversation"
	"github.com/013677890/LCchat-Backend/apps/msg/internal/domain/message"
	"github.com/013677890/LCchat-Backend/apps/msg/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/msg/internal/usecase"
)

// Injectors from wire.go:

func initializeMsgApp() (*MsgApp, error) {
	loggerConfig := provideLoggerConfig()
	logger, err := provideLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	mainMsgMetricsAddress := provideMsgMetricsAddress()
	mySQLConfig := provideMySQLConfig()
	db, err := provideMySQLDB(logger, mySQLConfig)
	if err != nil {
		return nil, err
	}
	repository := conversation.NewRepository(db)
	mainMsgGroupGRPCAddress := provideMsgGroupGRPCAddress()
	mainMsgGroupGRPCConn, err := provideMsgGroupGRPCConn(logger, mainMsgGroupGRPCAddress)
	if err != nil {
		return nil, err
	}
	client := provideMsgGroupClient(mainMsgGroupGRPCConn)
	service := provideConvService(repository, client)
	redisConfig := provideRedisConfig()
	redisClient, err := provideRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	messageRepository := message.NewRepository(db, redisClient)
	config := provideMsgConfig()
	messageService := provideMsgService(messageRepository, config, client)
	messageReadWorkflow := usecase.NewMessageReadWorkflow(messageService, service)
	mainMsgRelationGRPCAddress := provideMsgRelationGRPCAddress()
	mainMsgRelationGRPCConn, err := provideMsgRelationGRPCConn(logger, mainMsgRelationGRPCAddress)
	if err != nil {
		return nil, err
	}
	permissionChecker := provideMsgPermissionChecker(mainMsgRelationGRPCConn, mainMsgGroupGRPCConn)
	sendMessageWorkflow := usecase.NewSendMessageWorkflow(messageService, service, permissionChecker)
	recallMessageWorkflow := usecase.NewRecallMessageWorkflow(messageService)
	markReadWorkflow := usecase.NewMarkReadWorkflow(service)
	msgHandler := handler.NewMsgHandler(service, messageReadWorkflow, sendMessageWorkflow, recallMessageWorkflow, markReadWorkflow)
	registrationFunc := provideMsgRegistration(msgHandler)
	mainMsgGRPCAddress := provideMsgGRPCAddress()
	builtServer, err := provideMsgGRPCServer(registrationFunc)
	if err != nil {
		return nil, err
	}
	server := provideMsgMetricsServer(mainMsgMetricsAddress, builtServer)
	listener, err := provideMsgGRPCListener(mainMsgGRPCAddress)
	if err != nil {
		return nil, err
	}
	mainMsgGRPCShutdownTimeout := provideMsgGRPCShutdownTimeout()
	asyncConfig := provideAsyncConfig()
	pool, err := provideAsyncPool(logger, asyncConfig)
	if err != nil {
		return nil, err
	}
	mainMsgAsyncReleaseTimeout := provideAsyncReleaseTimeout(asyncConfig)
	kafkaConfig := provideKafkaConfig()
	groupMembershipProjectorRepository := conversation.NewGroupMembershipProjectorRepository(db)
	groupMembershipProjector, err := provideMsgGroupMembershipProjector(kafkaConfig, groupMembershipProjectorRepository, db)
	if err != nil {
		return nil, err
	}
	msgApp, err := NewMsgApp(logger, server, builtServer, listener, mainMsgGRPCShutdownTimeout, pool, mainMsgAsyncReleaseTimeout, groupMembershipProjector, db, redisClient)
	if err != nil {
		return nil, err
	}
	return msgApp, nil
}
