// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/msg/internal/domain/conversation"
	"github.com/013677890/LCchat-Backend/apps/msg/internal/domain/message"
	"github.com/013677890/LCchat-Backend/apps/msg/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/msg/internal/usecase"
)

// Injectors from wire.go:

func initializeMsgApp() (*MsgApp, error) {
	loggerConfig := provideLoggerConfig()
	logger, err := provideLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	mainMsgMetricsAddress := provideMsgMetricsAddress()
	mySQLConfig := provideMySQLConfig()
	db, err := provideMySQLDB(logger, mySQLConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideRedisConfig()
	client, err := provideRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	repository := message.NewRepository(db, client)
	config := provideMsgConfig()
	mainMsgGroupGRPCAddress := provideMsgGroupGRPCAddress()
	mainMsgGroupGRPCConn, err := provideMsgGroupGRPCConn(logger, mainMsgGroupGRPCAddress)
	if err != nil {
		return nil, err
	}
	groupcliClient := provideMsgGroupClient(mainMsgGroupGRPCConn)
	service := provideMsgService(repository, config, groupcliClient)
	conversationRepository := conversation.NewRepository(db)
	conversationService := conversation.NewService(conversationRepository)
	mainMsgRelationGRPCAddress := provideMsgRelationGRPCAddress()
	mainMsgRelationGRPCConn, err := provideMsgRelationGRPCConn(logger, mainMsgRelationGRPCAddress)
	if err != nil {
		return nil, err
	}
	permissionChecker := provideMsgPermissionChecker(mainMsgRelationGRPCConn, mainMsgGroupGRPCConn)
	sendMessageWorkflow := usecase.NewSendMessageWorkflow(service, conversationService, groupcliClient, permissionChecker)
	recallMessageWorkflow := usecase.NewRecallMessageWorkflow(service)
	markReadWorkflow := usecase.NewMarkReadWorkflow(conversationService)
	msgHandler := handler.NewMsgHandler(service, conversationService, sendMessageWorkflow, recallMessageWorkflow, markReadWorkflow)
	registrationFunc := provideMsgRegistration(msgHandler)
	mainMsgGRPCAddress := provideMsgGRPCAddress()
	builtServer, err := provideMsgGRPCServer(registrationFunc, mainMsgGRPCAddress)
	if err != nil {
		return nil, err
	}
	server := provideMsgMetricsServer(mainMsgMetricsAddress, builtServer)
	listener, err := provideMsgGRPCListener(mainMsgGRPCAddress)
	if err != nil {
		return nil, err
	}
	mainMsgGRPCShutdownTimeout := provideMsgGRPCShutdownTimeout()
	asyncConfig := provideAsyncConfig()
	pool, err := provideAsyncPool(logger, asyncConfig)
	if err != nil {
		return nil, err
	}
	mainMsgAsyncReleaseTimeout := provideAsyncReleaseTimeout(asyncConfig)
	msgApp, err := NewMsgApp(logger, server, builtServer, listener, mainMsgGRPCShutdownTimeout, pool, mainMsgAsyncReleaseTimeout, db, client)
	if err != nil {
		return nil, err
	}
	return msgApp, nil
}
