// Code generated by Wire. DO NOT EDIT.



//go:generate go run -mod=mod github.com/google/wire/cmd/wire

//go:build !wireinject

// +build !wireinject



package main



import (

	"github.com/013677890/LCchat-Backend/apps/msg/internal/domain/conversation"

	"github.com/013677890/LCchat-Backend/apps/msg/internal/domain/message"

	"github.com/013677890/LCchat-Backend/apps/msg/internal/handler"

	"github.com/013677890/LCchat-Backend/apps/msg/internal/usecase"

)



// Injectors from wire.go:



func initializeMsgApp() (*MsgApp, error) {

	loggerConfig := provideLoggerConfig()

	logger, err := provideLogger(loggerConfig)

	if err != nil {

		return nil, err

	}

	mainMetricsAddress := provideMetricsAddress()

	mySQLConfig := provideMySQLConfig()

	db, err := provideMySQLDB(logger, mySQLConfig)

	if err != nil {

		return nil, err

	}

	redisConfig := provideRedisConfig()

	client, err := provideRedisClient(logger, redisConfig)

	if err != nil {

		return nil, err

	}

	repository := message.NewRepository(db, client)

	config := provideMsgConfig()

	mainMsgUserGRPCAddress := provideMsgUserGRPCAddress()

	clientConn, err := provideMsgUserGRPCConn(logger, mainMsgUserGRPCAddress)

	if err != nil {

		return nil, err

	}

	mainMsgRelationGRPCAddress := provideMsgRelationGRPCAddress()

	clientConn2, err := provideMsgRelationGRPCConn(logger, mainMsgRelationGRPCAddress)

	if err != nil {

		return nil, err

	}

	groupClient := provideMsgGroupClient(clientConn)

	permissionChecker := provideMsgPermissionChecker(clientConn2, clientConn)

	service := provideMsgService(repository, config, groupClient)

	conversationRepository := conversation.NewRepository(db)

	conversationService := conversation.NewService(conversationRepository)

	kafkaConfig := provideKafkaConfig()

	producer := provideKafkaProducer(kafkaConfig)

	mqProducer := provideMsgProducer(kafkaConfig, producer)

	sendMessageWorkflow := usecase.NewSendMessageWorkflow(service, conversationService, mqProducer, groupClient, permissionChecker)

	recallMessageWorkflow := usecase.NewRecallMessageWorkflow(service, mqProducer)

	markReadWorkflow := usecase.NewMarkReadWorkflow(conversationService, mqProducer)

	msgHandler := handler.NewMsgHandler(service, conversationService, sendMessageWorkflow, recallMessageWorkflow, markReadWorkflow)

	registrationFunc := provideMsgRegistration(msgHandler)

	mainGrpcAddress := provideGRPCAddress()

	builtServer, err := provideMsgGRPCServer(registrationFunc, mainGrpcAddress)

	if err != nil {

		return nil, err

	}

	server := provideMetricsServer(mainMetricsAddress, builtServer)

	listener, err := provideMsgGRPCListener(mainGrpcAddress)

	if err != nil {

		return nil, err

	}

	mainMsgGRPCShutdownTimeout := provideGRPCShutdownTimeout()

	asyncConfig := provideAsyncConfig()

	pool, err := provideAsyncPool(logger, asyncConfig)

	if err != nil {

		return nil, err

	}

	mainMsgAsyncReleaseTimeout := provideAsyncReleaseTimeout(asyncConfig)

	msgApp, err := NewMsgApp(logger, server, builtServer, listener, mainMsgGRPCShutdownTimeout, pool, mainMsgAsyncReleaseTimeout, db, client, producer)

	if err != nil {

		return nil, err

	}

	return msgApp, nil

}

