// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/connect/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/connect/internal/svc"
)

// Injectors from wire.go:

func initializeConnectApp() (*ConnectApp, error) {
	loggerConfig := provideConnectLoggerConfig()
	logger, err := provideConnectLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	connectionManager := provideConnectManager()
	redisConfig := provideConnectRedisConfig()
	client, err := provideConnectRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	mainConnectAuthGRPCAddress := provideConnectAuthGRPCAddress()
	clientConn, err := provideAuthGRPCConn(logger, mainConnectAuthGRPCAddress)
	if err != nil {
		return nil, err
	}
	deviceServiceClient := provideAuthDeviceClient(clientConn)
	connectService := svc.NewConnectService(client, deviceServiceClient)
	wsHandler := handler.NewWSHandler(connectionManager, connectService)
	server := provideConnectHTTPServer(wsHandler, connectionManager)
	mainConnectGRPCAddress := provideConnectGRPCAddress()
	grpcServer := provideConnectGRPCServer(mainConnectGRPCAddress, connectionManager)
	deviceActiveConfig := provideConnectDeviceActiveConfig()
	connectApp, err := NewConnectApp(logger, server, grpcServer, connectionManager, connectService, clientConn, deviceActiveConfig)
	if err != nil {
		return nil, err
	}
	return connectApp, nil
}
