// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/group/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/group/internal/repository"
	"github.com/013677890/LCchat-Backend/apps/group/internal/service"
)

// Injectors from wire.go:

// initializeGroupApp 是 group-service 的依赖注入入口。
//
// 设计上保持和 auth / user / relation / msg 一致：
//  1. 手写 wire.go 只描述依赖图，不包含实际构造细节；
//  2. 生成后的 wire_gen.go 才是编译期真正参与构建的实现；
//  3. 这样既方便阅读依赖结构，也方便后续扩展 provider set。
func initializeGroupApp() (*GroupApp, error) {
	loggerConfig := provideGroupLoggerConfig()
	logger, err := provideGroupLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	mainGroupMetricsAddress := provideGroupMetricsAddress()
	mySQLConfig := provideGroupMySQLConfig()
	db, err := provideGroupMySQLDB(logger, mySQLConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideGroupRedisConfig()
	client, err := provideGroupRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	iGroupRepository := repository.NewGroupRepository(db, client)
	iGroupService := service.NewGroupService(iGroupRepository)
	groupHandler := handler.NewGroupHandler(iGroupService)
	registrationFunc := provideGroupRegistration(groupHandler)
	mainGroupGRPCAddress := provideGroupGRPCAddress()
	builtServer, err := provideGroupGRPCServer(registrationFunc, mainGroupGRPCAddress)
	if err != nil {
		return nil, err
	}
	server := provideGroupMetricsServer(mainGroupMetricsAddress, builtServer)
	listener, err := provideGroupGRPCListener(mainGroupGRPCAddress)
	if err != nil {
		return nil, err
	}
	mainGroupGRPCShutdownTimeout := provideGroupGRPCShutdownTimeout()
	asyncConfig := provideGroupAsyncConfig()
	pool, err := provideGroupAsyncPool(logger, asyncConfig)
	if err != nil {
		return nil, err
	}
	mainGroupAsyncReleaseTimeout := provideGroupAsyncReleaseTimeout(asyncConfig)
	kafkaConfig := provideGroupKafkaConfig()
	iGroupCacheProjectorRepository := repository.NewGroupCacheProjectorRepository(db, client)
	cacheProjector := provideGroupCacheProjector(kafkaConfig, iGroupCacheProjectorRepository, db)
	groupApp, err := NewGroupApp(logger, server, builtServer, listener, mainGroupGRPCShutdownTimeout, pool, mainGroupAsyncReleaseTimeout, cacheProjector, db, client)
	if err != nil {
		return nil, err
	}
	return groupApp, nil
}
