// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/013677890/LCchat-Backend/apps/auth/internal/handler"
	"github.com/013677890/LCchat-Backend/apps/auth/internal/repository"
	"github.com/013677890/LCchat-Backend/apps/auth/internal/service"
)

// Injectors from wire.go:

func initializeAuthApp() (*AuthApp, error) {
	loggerConfig := provideAuthLoggerConfig()
	logger, err := provideAuthLogger(loggerConfig)
	if err != nil {
		return nil, err
	}
	mainAuthMetricsAddress := provideAuthMetricsAddress()
	mySQLConfig := provideAuthMySQLConfig()
	db, err := provideAuthMySQLDB(logger, mySQLConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := provideAuthRedisConfig()
	client, err := provideAuthRedisClient(logger, redisConfig)
	if err != nil {
		return nil, err
	}
	iAuthRepository := repository.NewAuthRepository(db, client)
	iDeviceRepository := repository.NewDeviceRepository(db, client)
	iAuthService := service.NewAuthService(iAuthRepository, iDeviceRepository)
	authHandler := handler.NewAuthHandler(iAuthService)
	iDeviceService := service.NewDeviceService(iDeviceRepository)
	deviceHandler := handler.NewDeviceHandler(iDeviceService)
	iAccountService := service.NewAccountService(iAuthRepository, iDeviceRepository)
	accountHandler := handler.NewAccountHandler(iAccountService)
	iInternalAuthService := service.NewInternalAuthService(iAuthRepository)
	internalAuthHandler := handler.NewInternalAuthHandler(iInternalAuthService)
	registrationFunc := provideAuthRegistration(authHandler, deviceHandler, accountHandler, internalAuthHandler)
	mainAuthGRPCAddress := provideAuthGRPCAddress()
	builtServer, err := provideAuthGRPCServer(registrationFunc, mainAuthGRPCAddress)
	if err != nil {
		return nil, err
	}
	server := provideAuthMetricsServer(mainAuthMetricsAddress, builtServer)
	listener, err := provideAuthGRPCListener(mainAuthGRPCAddress)
	if err != nil {
		return nil, err
	}
	mainAuthGRPCShutdownTimeout := provideAuthGRPCShutdownTimeout()
	kafkaConfig := provideAuthKafkaConfig()
	producer := provideAuthKafkaProducer(client, kafkaConfig)
	v := provideAuthRedisRetryConsumer(client, kafkaConfig, logger, db)
	profileDisplayChangedConsumer := provideAuthProfileDisplayChangedConsumer(kafkaConfig, iInternalAuthService, db)
	authApp, err := NewAuthApp(logger, server, builtServer, listener, mainAuthGRPCShutdownTimeout, v, profileDisplayChangedConsumer, producer, db, client)
	if err != nil {
		return nil, err
	}
	return authApp, nil
}
