SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;
CREATE DATABASE IF NOT EXISTS `chat_server`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE `chat_server`;
CREATE USER IF NOT EXISTS 'debezium'@'%' IDENTIFIED BY 'debezium';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'debezium'@'%';
CREATE TABLE IF NOT EXISTS `outbox_events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增事件ID',
  `event_type` VARCHAR(128) NOT NULL COMMENT '领域事件类型',
  `entity_id` VARCHAR(64) NOT NULL COMMENT '事件分区键（通常是 user_uuid）',
  `payload` LONGTEXT NOT NULL COMMENT '事件负载 JSON',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_outbox_event_type_created` (`event_type`, `created_at`),
  KEY `idx_outbox_entity_id` (`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CDC Outbox 事件表';
CREATE TABLE IF NOT EXISTS `idempotent_events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `event_type` VARCHAR(64) NOT NULL COMMENT '事件类型',
  `event_id` VARCHAR(64) NOT NULL COMMENT '事件唯一ID',
  `processed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '处理时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_type_event` (`event_type`, `event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='幂等消费记录表';
CREATE TABLE IF NOT EXISTS `dead_events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `source` VARCHAR(128) NOT NULL COMMENT '来源消费者标识(service:topic)',
  `topic` VARCHAR(191) NOT NULL COMMENT 'Kafka topic',
  `kafka_partition` INT NOT NULL DEFAULT 0 COMMENT 'Kafka 分区',
  `kafka_offset` BIGINT NOT NULL DEFAULT 0 COMMENT 'Kafka offset',
  `msg_key` VARCHAR(191) NOT NULL DEFAULT '' COMMENT 'Kafka 消息 key',
  `event_type` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '事件类型(尽力解析)',
  `payload` LONGBLOB NOT NULL COMMENT '原始消息字节',
  `error_msg` TEXT COMMENT '最后一次失败错误',
  `attempts` INT NOT NULL DEFAULT 0 COMMENT '原地重试次数',
  `status` VARCHAR(16) NOT NULL DEFAULT 'pending' COMMENT 'pending|replayed|discarded',
  `first_failed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '首次失败时间',
  `last_failed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '最后失败时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_dead_source_status` (`source`, `status`),
  KEY `idx_dead_status_created` (`status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='消费死信(队头阻塞旁路)';
CREATE TABLE IF NOT EXISTS `user_account` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `user_uuid` CHAR(20) NOT NULL COMMENT '用户唯一id',
  `email` VARCHAR(100) NOT NULL COMMENT '邮箱',
  `telephone` VARCHAR(20) DEFAULT NULL COMMENT '电话',
  `password_hash` CHAR(60) NOT NULL COMMENT '密码哈希',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态,0.正常 1.注销',
  `is_admin` TINYINT NOT NULL DEFAULT 0 COMMENT '是否是管理员,0.不是 1.是',
  `login_nickname` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '登录展示昵称(冗余)',
  `login_avatar` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '登录展示头像(冗余)',
  `last_login_at` DATETIME(3) DEFAULT NULL COMMENT '最近登录时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` DATETIME(3) DEFAULT NULL COMMENT '注销时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_account_uuid` (`user_uuid`),
  UNIQUE KEY `uk_user_account_telephone` (`telephone`),
  UNIQUE KEY `uk_user_account_email` (`email`),
  KEY `idx_user_account_created_at` (`created_at`),
  KEY `idx_user_account_deleted_at` (`deleted_at`),
  KEY `idx_user_account_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户账号信息';
CREATE TABLE IF NOT EXISTS `user_profile` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `user_uuid` CHAR(20) NOT NULL COMMENT '用户唯一id',
  `nickname` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '昵称',
  `avatar` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像',
  `gender` TINYINT NOT NULL DEFAULT 3 COMMENT '性别,1.男 2.女 3.未知',
  `signature` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '个性签名',
  `birthday` DATE DEFAULT NULL COMMENT '生日',
  `qrcode_token` VARCHAR(64) DEFAULT NULL COMMENT '二维码token',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_profile_user_uuid` (`user_uuid`),
  KEY `idx_user_profile_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户资料信息';
CREATE TABLE IF NOT EXISTS `groups` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `uuid` CHAR(20) NOT NULL COMMENT '群组唯一id',
  `name` VARCHAR(64) NOT NULL COMMENT '群名称',
  `notice` VARCHAR(500) DEFAULT NULL COMMENT '群公告',
  `member_cnt` INT NOT NULL DEFAULT 1 COMMENT '群人数',
  `owner_uuid` CHAR(20) NOT NULL COMMENT '群主uuid',
  `add_mode` TINYINT NOT NULL DEFAULT 0 COMMENT '加群方式,0.直接 1.审核',
  `mute_all` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否全员禁言,0否 1是',
  `avatar` VARCHAR(255) NOT NULL DEFAULT 'https://cube.elemecdn.com/0/88/03b0d39583f48206768a7534e55bcpng.png' COMMENT '群头像URL',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态,0.正常 1.禁用 2.解散',
  `cache_version` BIGINT NOT NULL DEFAULT 0 COMMENT '群缓存投影严格递增版本',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` DATETIME(3) DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_groups_uuid` (`uuid`),
  KEY `idx_groups_owner_uuid` (`owner_uuid`),
  KEY `idx_groups_status` (`status`),
  KEY `idx_groups_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='群基础信息';
CREATE TABLE IF NOT EXISTS `group_members` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `group_uuid` CHAR(20) NOT NULL COMMENT '群uuid',
  `user_uuid` CHAR(20) NOT NULL COMMENT '用户uuid',
  `role` TINYINT NOT NULL DEFAULT 0 COMMENT '0成员 1管理员 2群主',
  `remark` VARCHAR(64) DEFAULT NULL COMMENT '群名片/备注',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0正常 1退出 2踢出 3待审核',
  `mute_until` DATETIME(3) DEFAULT NULL COMMENT '禁言到期时间',
  `inviter_uuid` CHAR(20) DEFAULT NULL COMMENT '邀请人uuid',
  `joined_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '入群时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` DATETIME(3) DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_group_user` (`group_uuid`, `user_uuid`),
  KEY `idx_group_members_group_uuid` (`group_uuid`),
  KEY `idx_group_members_user_uuid` (`user_uuid`),
  KEY `idx_group_members_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='群成员关系';
CREATE TABLE IF NOT EXISTS `group_join_requests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `group_uuid` CHAR(20) NOT NULL COMMENT '群uuid',
  `applicant_uuid` CHAR(20) NOT NULL COMMENT '申请人uuid',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0待处理 1通过 2拒绝 3撤销',
  `reason` VARCHAR(255) DEFAULT NULL COMMENT '申请附言',
  `reviewer_uuid` CHAR(20) DEFAULT NULL COMMENT '处理人uuid',
  `review_remark` VARCHAR(255) DEFAULT NULL COMMENT '处理备注',
  `reviewed_at` DATETIME(3) DEFAULT NULL COMMENT '处理时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` DATETIME(3) DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `idx_group_join_pending` (`group_uuid`, `status`, `deleted_at`, `created_at`, `id`),
  KEY `idx_group_join_applicant` (`applicant_uuid`, `status`, `deleted_at`, `created_at`, `id`),
  KEY `idx_group_join_group_applicant_id` (`group_uuid`, `applicant_uuid`, `deleted_at`, `id`),
  KEY `idx_group_join_reviewed` (`group_uuid`, `status`, `deleted_at`, `reviewed_at`, `id`),
  KEY `idx_group_join_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='群入群申请';
CREATE TABLE IF NOT EXISTS `user_relations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `user_uuid` CHAR(20) NOT NULL COMMENT '用户uuid',
  `peer_uuid` CHAR(20) NOT NULL COMMENT '对端用户uuid',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '关系状态 0.正常 1.拉黑(原先为好友) 2.删除 3.拉黑(原先非好友)',
  `remark` VARCHAR(64) DEFAULT NULL COMMENT '好友备注',
  `source` VARCHAR(64) DEFAULT NULL COMMENT '添加来源',
  `group_tag` VARCHAR(32) DEFAULT NULL COMMENT '标签',
  `blacklisted_at` DATETIME(3) DEFAULT NULL COMMENT '拉黑时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` DATETIME(3) DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_user_peer` (`user_uuid`, `peer_uuid`),
  KEY `idx_user_updated_at` (`user_uuid`, `updated_at`),
  KEY `idx_peer_uuid` (`peer_uuid`),
  KEY `idx_user_status_deleted_created` (`user_uuid`, `status`, `deleted_at`, `created_at`, `id`),
  KEY `idx_user_blacklist_deleted_time` (`user_uuid`, `status`, `deleted_at`, `blacklisted_at`, `id`),
  KEY `idx_user_relations_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户单向关系';
CREATE TABLE IF NOT EXISTS `apply_requests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `apply_type` TINYINT NOT NULL COMMENT '0好友 1加群',
  `applicant_uuid` CHAR(20) NOT NULL COMMENT '申请人uuid',
  `target_uuid` CHAR(20) NOT NULL COMMENT '目标uuid',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0待处理 1通过 2拒绝 3过期',
  `is_read` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '申请是否已读',
  `reason` VARCHAR(255) DEFAULT NULL COMMENT '申请附言',
  `source` VARCHAR(32) DEFAULT NULL COMMENT '申请来源',
  `handle_user_uuid` CHAR(20) DEFAULT NULL COMMENT '处理人uuid',
  `handle_remark` VARCHAR(255) DEFAULT NULL COMMENT '处理备注',
  `expired_at` DATETIME(3) DEFAULT NULL COMMENT '过期时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` DATETIME(3) DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `idx_applicant_target` (`applicant_uuid`, `target_uuid`),
  KEY `idx_apply_pending_list` (`apply_type`, `target_uuid`, `status`, `deleted_at`, `created_at`, `id`),
  KEY `idx_apply_sent_list` (`apply_type`, `applicant_uuid`, `status`, `deleted_at`, `created_at`, `id`),
  KEY `idx_apply_target_read` (`target_uuid`, `apply_type`, `is_read`, `deleted_at`),
  KEY `idx_apply_requests_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='好友/加群申请';
CREATE TABLE IF NOT EXISTS `device_sessions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_uuid` CHAR(20) NOT NULL COMMENT '用户uuid',
  `device_id` VARCHAR(64) NOT NULL COMMENT '设备唯一指纹',
  `device_name` VARCHAR(64) NOT NULL DEFAULT 'Unknown Device' COMMENT '设备名称',
  `platform` VARCHAR(32) NOT NULL COMMENT '平台',
  `app_version` VARCHAR(32) DEFAULT NULL COMMENT 'APP版本',
  `ip` VARCHAR(64) DEFAULT NULL COMMENT '登录IP',
  `user_agent` VARCHAR(512) DEFAULT NULL COMMENT 'User Agent',
  `expire_at` DATETIME(3) DEFAULT NULL COMMENT '过期时间',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_user_device` (`user_uuid`, `device_id`),
  KEY `idx_device_expire_at` (`expire_at`),
  KEY `idx_device_deleted_at` (`deleted_at`),
  KEY `idx_device_user_updated` (`user_uuid`, `updated_at`, `id`),
  KEY `idx_device_user_status_deleted` (`user_uuid`, `status`, `deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备会话';
CREATE TABLE IF NOT EXISTS `conversation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `conv_id` VARCHAR(128) NOT NULL COMMENT '会话ID',
  `type` TINYINT NOT NULL COMMENT '1单聊 2群聊',
  `owner_uuid` CHAR(20) NOT NULL COMMENT '会话归属用户uuid',
  `target_uuid` CHAR(20) NOT NULL COMMENT '单聊为对端uuid，群聊为群uuid',
  `last_msg_id` CHAR(64) DEFAULT NULL COMMENT '最后消息ID',
  `last_msg_at` DATETIME(3) DEFAULT NULL COMMENT '最后消息时间',
  `last_msg_preview` VARCHAR(255) DEFAULT NULL COMMENT '最后消息预览JSON',
  `max_seq` BIGINT NOT NULL DEFAULT 0 COMMENT '会话内当前最大seq',
  `read_seq` BIGINT NOT NULL DEFAULT 0 COMMENT '已读最大seq',
  `clear_seq` BIGINT NOT NULL DEFAULT 0 COMMENT '会话清空位点',
  `unread_count` BIGINT NOT NULL DEFAULT 0 COMMENT '未读数',
  `mute` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '免打扰',
  `pin` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '置顶',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '用户个人会话状态:0正常 1关闭/删除',
  `membership_status` TINYINT NOT NULL DEFAULT 0 COMMENT '群成员投影状态:0不适用(P2P) 1有效成员 2已退出',
  `membership_version` BIGINT NOT NULL DEFAULT 0 COMMENT '最后生效的group投影版本',
  `membership_joined_at` DATETIME(3) DEFAULT NULL COMMENT '本次有效成员关系的入群时间',
  `membership_left_at` DATETIME(3) DEFAULT NULL COMMENT '成员退出或被移除时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_owner_conv` (`owner_uuid`, `target_uuid`),
  KEY `idx_owner_status_update` (`owner_uuid`, `status`, `updated_at`),
  KEY `idx_owner_type_membership` (`owner_uuid`, `type`, `membership_status`, `status`),
  KEY `idx_conversation_deleted_at` (`deleted_at`),
  CONSTRAINT `chk_conversation_membership_status`
    CHECK ((`type` = 1 AND `membership_status` = 0) OR (`type` = 2 AND `membership_status` IN (1, 2))),
  CONSTRAINT `chk_conversation_membership_version` CHECK (`membership_version` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会话元数据';
CREATE TABLE IF NOT EXISTS `message` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `conv_id` VARCHAR(128) NOT NULL COMMENT '会话ID',
  `seq` BIGINT NOT NULL COMMENT '会话内序号',
  `msg_id` CHAR(64) NOT NULL COMMENT '全局消息ID',
  `client_msg_id` CHAR(64) NOT NULL COMMENT '客户端幂等ID',
  `from_uuid` CHAR(20) NOT NULL COMMENT '发送者uuid',
  `device_id` CHAR(64) NOT NULL COMMENT '发送设备ID',
  `msg_type` SMALLINT NOT NULL COMMENT '消息类型',
  `content` JSON NOT NULL COMMENT '消息内容JSON',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0正常 1撤回 2删除',
  `reply_to_msg_id` CHAR(64) NOT NULL DEFAULT '' COMMENT '引用消息ID',
  `at_users` JSON DEFAULT NULL COMMENT '被@用户UUID列表',
  `send_time` DATETIME(3) DEFAULT NULL COMMENT '发送时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_message_msg_id` (`msg_id`),
  UNIQUE KEY `uidx_sender_client` (`client_msg_id`, `from_uuid`, `device_id`),
  UNIQUE KEY `uidx_conv_seq` (`conv_id`, `seq`),
  KEY `idx_conv_time` (`conv_id`, `send_time`),
  KEY `idx_message_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='聊天消息';
CREATE TABLE IF NOT EXISTS `group_conversation` (
  `group_uuid` CHAR(20) NOT NULL COMMENT '群组唯一id(业务主键，一对一关系无需自增ID)',
  `max_seq` BIGINT NOT NULL DEFAULT 0 COMMENT '群消息当前最大seq',
  `last_msg_id` CHAR(64) DEFAULT NULL COMMENT '最后一条消息的ID(ULID)',
  `last_msg_preview` VARCHAR(255) DEFAULT NULL COMMENT '最后消息预览',
  `last_msg_at` DATETIME(3) DEFAULT NULL COMMENT '群首次可见或最后消息时间(做活跃度排序)',
  `group_status` TINYINT NOT NULL DEFAULT 0 COMMENT 'group-service群状态:0正常 1禁用 2解散',
  `projection_version` BIGINT NOT NULL DEFAULT 0 COMMENT '最后连续消费的group.cache投影版本',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '状态最后变更时间',
  PRIMARY KEY (`group_uuid`),
  KEY `idx_last_msg_at` (`last_msg_at`),
  CONSTRAINT `chk_group_conversation_status` CHECK (`group_status` IN (0, 1, 2)),
  CONSTRAINT `chk_group_conversation_projection_version` CHECK (`projection_version` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='群会话状态(热数据,每条群消息更新一次)';
FLUSH PRIVILEGES;
SET FOREIGN_KEY_CHECKS = 1;
