apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lcchat-dev

resources:
  - namespace.yaml
  - external-infra.yaml
  - ../../base

images:
  - name: lcchat
    newName: lcchat
    newTag: dev-bin

patches:
  - path: patches/replicas.yaml
  - path: patches/dev-configmap.yaml
  - path: patches/dev-secret.yaml
